#### Creating a logistic regression to predict absenteeism

In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

##### Creating Targets

In [3]:
data_preprocessed["Absenteeism Time in Hours"].median()

3.0

In [4]:
targets = np.where(data_preprocessed["Absenteeism Time in Hours"] > 
                   data_preprocessed["Absenteeism Time in Hours"].median(), 1, 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [7]:
# checking the balance between the two outputs
targets.sum()/ targets.shape[0] # checking the %

0.45571428571428574

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week', 'Daily Work Load Average', 'Distance to Work'], axis = 1)

In [9]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

##### Selecting the Inputs for the Regression

In [10]:
data_with_targets.shape

(700, 12)

In [11]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [45]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

##### Standardize the data

In [46]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scalar = StandardScaler()

In [47]:
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns= self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled,X_scaled], axis=1)[init_col_order]

In [48]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [49]:
# columns_to_scale = ['Month Value', 'Day of the week', 'Transportation Expense', 'Distance to Work',
#        'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
#        'Children', 'Pets']

columns_to_omit = ['Reason_1',"Reason_2",'Reason_3','Reason_3',"Education"]

columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [50]:
absenteeism_scalar = CustomScaler(columns_to_scale)
absenteeism_scalar.fit(unscaled_inputs)

D:\Anaconda\envs\py3-TF2.0\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Reason_4', 'Month Value', 'Transportation Expense',
                      'Age', 'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [51]:
scaled_inputs = absenteeism_scalar.transform(unscaled_inputs)

In [52]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0  0.821365     0.182726   
1           0         0         0 -1.217485     0.182726   
2           0         0         0  0.821365     0.182726   
3           1         0         0 -1.217485     0.182726   
4           0         0         0  0.821365     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0 -1.217485    -0.388293   
696         1         0         0 -1.217485    -0.388293   
697         1         0         0 -1.217485    -0.388293   
698         0         0         0  0.821365    -0.388293   
699         0         0         0  0.821365    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [53]:
scaled_inputs.shape

(700, 11)

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 178         1         0         0 -1.217485    -0.959313   
 393         0         0         0  0.821365    -0.959313   
 486         0         0         0  0.821365     0.468236   
 126         0         0         0  0.821365    -1.530333   
 594         0         0         1 -1.217485    -1.244823   
 ..        ...       ...       ...       ...          ...   
 242         0         0         0  0.821365     0.182726   
 203         0         0         0 -1.217485    -0.673803   
 522         0         0         0  0.821365     1.039256   
 467         0         0         0  0.821365     0.182726   
 327         1         0         0 -1.217485     1.324766   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 178                0.040034 -1.320435        -0.643782          0 -0.019280   
 393                0.568211 -0.065439        -0.878984          0  2.679969   
 486                1.0360

In [56]:
x_train ,x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [57]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


##### Model 

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [59]:
# Training the Model

In [60]:
reg = LogisticRegression()
reg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [61]:
reg.score(x_train, y_train)

0.7767857142857143

In [62]:
# Now we will check manually the Accuracy

In [63]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [64]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [65]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [66]:
np.sum(model_outputs == y_train)

435

In [67]:
model_outputs.shape[0]

560

In [68]:
np.sum(model_outputs == y_train)/model_outputs.shape[0] #manually checked accuracy

0.7767857142857143

In [69]:
# finding the intercepts and coefficents

In [70]:
reg.intercept_

array([-1.20144357])

In [71]:
reg.coef_

array([[ 2.95686426,  0.71803466,  3.28699461,  0.49156526,  0.16642345,
         0.61790963, -0.17337317,  0.28393749, -0.23837769,  0.34558496,
        -0.28171255]])

In [72]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [73]:
feature_name = unscaled_inputs.columns.values

In [74]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Coefficent'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficent
0                 Reason_1    2.956864
1                 Reason_2    0.718035
2                 Reason_3    3.286995
3                 Reason_4    0.491565
4              Month Value    0.166423
5   Transportation Expense    0.617910
6                      Age   -0.173373
7          Body Mass Index    0.283937
8                Education   -0.238378
9                 Children    0.345585
10                    Pets   -0.281713

In [75]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficent
0                Intercept   -1.201444
1                 Reason_1    2.956864
2                 Reason_2    0.718035
3                 Reason_3    3.286995
4                 Reason_4    0.491565
5              Month Value    0.166423
6   Transportation Expense    0.617910
7                      Age   -0.173373
8          Body Mass Index    0.283937
9                Education   -0.238378
10                Children    0.345585
11                    Pets   -0.281713

In [76]:
summary_table["Odds_ratio"] = np.exp(summary_table.Coefficent)
summary_table

Feature name  Coefficent  Odds_ratio
0                Intercept   -1.201444    0.300760
1                 Reason_1    2.956864   19.237553
2                 Reason_2    0.718035    2.050400
3                 Reason_3    3.286995   26.762311
4                 Reason_4    0.491565    1.634873
5              Month Value    0.166423    1.181073
6   Transportation Expense    0.617910    1.855046
7                      Age   -0.173373    0.840824
8          Body Mass Index    0.283937    1.328350
9                Education   -0.238378    0.787905
10                Children    0.345585    1.412816
11                    Pets   -0.281713    0.754491

In [77]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficent  Odds_ratio
3                 Reason_3    3.286995   26.762311
1                 Reason_1    2.956864   19.237553
2                 Reason_2    0.718035    2.050400
6   Transportation Expense    0.617910    1.855046
4                 Reason_4    0.491565    1.634873
10                Children    0.345585    1.412816
8          Body Mass Index    0.283937    1.328350
5              Month Value    0.166423    1.181073
7                      Age   -0.173373    0.840824
9                Education   -0.238378    0.787905
11                    Pets   -0.281713    0.754491
0                Intercept   -1.201444    0.300760

##### Testing the model

In [78]:
reg.score(x_test,y_test)

0.75

In [79]:
predicted_proba = reg.predict_proba(x_test)

In [80]:
predicted_proba

array([[0.7091507 , 0.2908493 ],
       [0.58123214, 0.41876786],
       [0.43208416, 0.56791584],
       [0.78098011, 0.21901989],
       [0.08374569, 0.91625431],
       [0.33553652, 0.66446348],
       [0.30148987, 0.69851013],
       [0.12938295, 0.87061705],
       [0.78676906, 0.21323094],
       [0.74674464, 0.25325536],
       [0.48511419, 0.51488581],
       [0.21919936, 0.78080064],
       [0.07043064, 0.92956936],
       [0.73589989, 0.26410011],
       [0.30993077, 0.69006923],
       [0.54560561, 0.45439439],
       [0.54438707, 0.45561293],
       [0.53257912, 0.46742088],
       [0.40726543, 0.59273457],
       [0.05136493, 0.94863507],
       [0.69644025, 0.30355975],
       [0.78098011, 0.21901989],
       [0.42033127, 0.57966873],
       [0.42033127, 0.57966873],
       [0.24568603, 0.75431397],
       [0.74421282, 0.25578718],
       [0.50541165, 0.49458835],
       [0.85917827, 0.14082173],
       [0.19884898, 0.80115102],
       [0.78098011, 0.21901989],
       [0.

In [81]:
predicted_proba.shape

(140, 2)

In [82]:
predicted_proba[:,-1]

array([0.2908493 , 0.41876786, 0.56791584, 0.21901989, 0.91625431,
       0.66446348, 0.69851013, 0.87061705, 0.21323094, 0.25325536,
       0.51488581, 0.78080064, 0.92956936, 0.26410011, 0.69006923,
       0.45439439, 0.45561293, 0.46742088, 0.59273457, 0.94863507,
       0.30355975, 0.21901989, 0.57966873, 0.57966873, 0.75431397,
       0.25578718, 0.49458835, 0.14082173, 0.80115102, 0.21901989,
       0.37334443, 0.67789359, 0.68530934, 0.53857119, 0.21901989,
       0.5389575 , 0.22131089, 0.73585391, 0.40652709, 0.60775209,
       0.21100091, 0.44177293, 0.23812036, 0.3625404 , 0.8310096 ,
       0.56744139, 0.68770893, 0.2908493 , 0.2205465 , 0.20319915,
       0.57167814, 0.2988982 , 0.66446348, 0.27340974, 0.83573118,
       0.44206084, 0.88687736, 0.22921982, 0.3049351 , 0.3150983 ,
       0.69520744, 0.65378839, 0.29315437, 0.79565111, 0.20554347,
       0.27164473, 0.07568906, 0.22131089, 0.7354169 , 0.30265143,
       0.22131089, 0.26433353, 0.90682792, 0.46486717, 0.60855

##### Saving the model

In [83]:
import pickle 

In [84]:
with open('model','wb') as file:
    pickle.dump(reg, file)

In [85]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scalar, file)